"""add column description to workspace table

Revision ID: cdba410537dd
Revises: 35af7e795fcf
Create Date: 2026-07-30 14:15:05.639230

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdba410537dd"
down_revision: str | Sequence[str] | None = "35af7e795fcf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=500), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
